sonar:
  stage: test
  variables:
    ANDROID_HOME: '/Users/swissdev/Library/Android'
  only:
    - master
  tags:
    - android
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=android-picker -Dsonar.host.url=https://sonar.swiss-dev.ch -Dsonar.login=$SONAR_LOGIN
